### ISSUE TITLE
[Suggestion] Consider make aclk and aresetn interface input

### ISSUE THREAD

**Issue by nbdd0121** [lowRISC/socip#1]
Current `aclk` and `aresetn` are connected separately.  Instead of doing this, we can simply add `aclk` and `aresetn` as input of interface `nasti_channel`. After this we will only need to hook up these two signals once when we instantiate interface, no need to hook it up separately. These two signals are part of NASTI, so combining them with the interface definition makes more sense than current implementation.

**Comment by wsong83** [comment]
But a module may have multiple AXI buses that sharing the same clk and reset, like the Rocket-chip now have at least two NASTI interfaces.

**Comment by nbdd0121** [comment]
If it is a requirement for two NASTI buses to have same clk and reset, then we can simply use any one of them, and use assertions on the other one to make sure wrong connections can be detected during simulation.

**Comment by wsong83** [comment]
Your way could work, but then it looks like a workaround.

Clock and reset are special signals. Enforcing the inclusive manner is actually limiting the flexibility.
Not having them in the interface leads to the overhead of manually adding and connecting clock and reset ports, but in reality, SV's automatic connection probably will do it for you as long as all modules using the same clock and reset names.
Having them in the interface leads to explicit clock assignment for even interface and complications when interfaces sharing clock signals.

I think the ultimate reason to not having them, is the reduced flexibility.

**Comment by nbdd0121** [comment]
I don't really see any flexibility loss here, since master and slaves connecting to the same channel must use same clock and reset signal, as suggested in AXI spec. By including them in interface input, we are actually enforcing necessary requirements.

**Comment by wsong83** [comment]
What about using the current nasti crossbar in socip as an example. Now it supports up to 8 input and output ports. Each input and output is individually enabled or disabled by valid (input) or address mask (output). If clock is bounded in interfaces, the crossbar itself would not known which clock to use without some complex conditions (no port is guaranteed used at all time).
